const { default: mongoose } = require("mongoose");

const User = new mongoose.Schema({
    /**
     * The ID of the user. Autogenerated by backend.
     */
    id: String,
    /**
     * The username of this user.
     */
    username: String,
    /**
     * The discriminant for this user. Autogenerated.
     */
    discrim: String,
    /**
     * The email for this user.
     */
    email: String,
    /**
     * The phone number of this user.
     */
    phone: String,
    /**
     * The avatar URL of this user. By default, a random colored image is selected from our CDN.
     */
    avatarUrl: String,
    /**
     * The hashed password of this user.
     */
    passwordHash: String,
    /**
     * The account verification status.
     *  - "VERIFIED_L1" specifies an account which has been verified with an email.
     *  - "VERIFIED_L2" specifies an account which has been verified with both an email and valid phone number.
     *  - "AWAIT_VERIF" specifies an account which has specified an email but their email has not been confirmed yet.
     *  - "UNVERIFIED" specifies an account which has not been verified. We clasify this as a new user.
     */
    verifStatus: String
});

module.exports = User;